Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/urls.py
from django.contrib import admin
from django.urls import path, include # Setup include to allow other app's urls to 
from . import views # COMO QUE NO EXISTE? XD

from django.conf import settings
from django.conf.urls.static import static
from .views import *
from ProyectoAPT.views import filtrar_estudiantes
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('', views.index, name='index'),
    # Horarios
    path('horarios/', views.registroHoras, name='horarios'),
    path('Horarios/<int:estudianteID>', views.tratamientosForm, name='tratamientosEstudiante'),
    # There we will enable the horario LIST
    path('obtener-horarios-disponibles/', views.obtener_horarios_disponibles, name='obtener_horarios_disponibles'),
    

    # Eliminar horario
    path('eliminar-horario/<int:horario_id>/', views.eliminar_horario, name='eliminar_horario'),



    # AUTH
    path('login/', views.loginUser, name='login'),
    path('registro/', views.register, name='registro'),
    path('logout/', views.custom_logout, name='logout'),
    path('obtener-direccion-universidad/', views.obtener_direccion_universidad, name='obtener_direccion_universidad'),
    path('revisar_estudiantes/', views.revisar_estudiantes, name='revisar_estudiantes'),
    #aptcha
    path('captcha/', include('captcha.urls')),
    #Servicios
    path('servicios/', views.servicios, name='servicios'),

    

    #Citas Paciente
    path('citas/', views.citas_pac, name='citas'),
    path('cita/anular/<int:cita_id>/', views.anular_cita, name='anular_cita'),

    # Añadir a subPage de Estudiante....
    path('estudiante/infopersonal/', views.infoestudiante, name="infoestudiante"),
    path('estudiante/notificaciones_estudiante/', views.notifiaciones_est, name="notificaciones"),
    path('estudiante/pacientes_estudiante/', views.pacientes_est, name="pacientes_est"),
    path('estudiante/calendario_est/',  views.calendar_est, name="calendario"), 
    path('crear_historial_medico/<int:paciente_id>/', views.crear_historial_medico, name='crear_historial_medico'),
    path('filtrar-estudiantes/', views.filtrar_estudiantes, name='filtrar_estudiantes'),


    #crear ficha paciente
    path('crear-ficha/<int:user_id>/', views.crear_ficha_paciente, name='crear_ficha_paciente'),
    path('lista_fichas_clinicas/', views.ver_ficha_clinica, name='lista_fichas_clinicas'),
    path('fichaExportar/<int:user_id>', views.exportar_ficha_paciente, name='fichaExportar'),
    #eliminar paciente
    path('eliminar-paciente/<int:paciente_id>/', views.eliminar_paciente, name='eliminar_paciente'),
    path('horarios/', filtrar_estudiantes, name='horarios'),  
    path('ver_ficha_clinica/<int:paciente_id>/', views.ver_ficha_clinica, name='ver_ficha_clinica'),
    

    # contraseña olvidada
    path('olvide-password/', 
        auth_views.PasswordResetView.as_view(
            template_name='login/olvide-pass.html',
            email_template_name='login/pass_email_reset.html',
            subject_template_name='login/password_reset_subject.txt',
        ),
        name='password_reset'
    ),
    path('reset-password-enviado/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='login/pass_confirm_email.html'
        ),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='login/reset-pass.html'
        ),
        name='password_reset_confirm'
    ),
    path('reset-password-completado/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='login/pass_complete.html'
        ),
        name='password_reset_complete'
    ),
    ]
# Solo en modo de desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager
from django.core.validators import FileExtensionValidator, MinLengthValidator, RegexValidator
from django.core.exceptions import ValidationError
# Create your models here.
from datetime import datetime
from django.utils import timezone
from datetime import date

#TipoUsuario
class TipoUsuario(models.Model):
        id= models.BigAutoField(primary_key=True)
        nombre_tipo_usuario = models.CharField(max_length=100)
        descripcion = models.CharField(max_length=100)
        def __str__(self):
            return str(self.nombre_tipo_usuario)
        # DICT
        #2.Estudiante
        #1.Paciente
        
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El usuario debe tener un email')
        email = self.normalize_email(email)
        extra_fields.setdefault('username', email.split('@')[0])  # Generar un username a partir del email
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('username', email.split('@')[0])

        if extra_fields.get('is_staff') is not True:
            raise ValueError('El superusuario debe tener is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('El superusuario debe tener is_superuser=True.')

        return self.create_user(email, password, **extra_fields)
    
    #filtros universidades y tratamientos
class Universidad(models.Model):
    id = models.BigAutoField(primary_key=True)
    nombre = models.CharField(max_length=100, unique=True)
    direccion = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.nombre


class tipoTratamiento(models.Model):
    id = models.BigAutoField(primary_key=True)
    nombreTratamiento= models.CharField(max_length=50)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombreTratamiento

class Comuna(models.Model):
    id = models.CharField(max_length=10, primary_key=True)  # Usamos id pero contendrá el código
    nombreComuna = models.CharField(max_length=50)

    class Meta:
        db_table = 'proyectoapt_comuna'  # Especificamos el nombre exacto de la tabla

    def __str__(self):
        return self.nombreComuna



def validar_fecha_nacimiento(fecha):
    if fecha >= date.today():
        return False
    return True
        
        
class customuser(AbstractUser):
    id = models.BigAutoField(primary_key=True)
    email = models.EmailField(unique=True, null=True)
    rut = models.CharField(max_length=13, unique=True, null=True)
    id_tipo_user = models.ForeignKey('TipoUsuario', on_delete=models.SET_NULL, null=True)
    descripcion = models.TextField(null=True, blank=True)
    imageBlob = models.ImageField(default="imagenes_usuario/profiledefault.jpg", upload_to='imagenes_usuario/', blank=True, null=True)
    fecha_nac = models.DateField(
        validators=[validar_fecha_nacimiento],
        null=True,  # Permitir null
        blank=True  # Permitir blank
    )
    num_tel = models.CharField(
        max_length=9,
        null=True,
        validators=[
            MinLengthValidator(9, message='Asegúrate de que el numero tenga al menos 9 digitos'),
            RegexValidator(
                regex=r'^\d{9}$',
                message='Ingresa un número válido de 9 dígitos'
            )
        ]
    )
    direccion = models.TextField(null=True, blank=True)
    universidad = models.ForeignKey(Universidad, on_delete=models.SET_NULL, null=True, blank=True)
    comuna = models.ForeignKey(Comuna, on_delete=models.SET_NULL, null=True, blank=True)
    tratamientos = models.ManyToManyField(tipoTratamiento, blank=True)
    Certificado = models.FileField(
        upload_to='documentos_estudiantes/',
        null=True,
        blank=True,
        validators=[
            FileExtensionValidator(
                allowed_extensions=['pdf'],
                message='Solo se permiten archivos PDF'
            )
        ],
        help_text='Sube un certificado en formato PDF'
    )

    # Nuevo campo para manejar el estado de aprobación
    ESTADO_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('aprobado', 'Aprobado'),
        ('rechazado', 'Rechazado')
    ]
    estado_aprobacion = models.CharField(max_length=10, choices=ESTADO_CHOICES, default='pendiente')

    USERNAME_FIELD = 'email'  # Usar email para el inicio de sesión
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def clean(self):
        # Si es staff, no hacemos validaciones
        if self.is_staff:
            return
        
        super().clean()
        # Validaciones solo para usuarios no staff
        if self.fecha_nac and self.fecha_nac >= date.today():
            raise ValidationError({
                'fecha_nac': 'La fecha de nacimiento no puede ser la misma de hoy o futura.'
            })
        
        # Validación del certificado solo para estudiantes no staff
        if not self.pk:  # Si es un nuevo usuario
            if self.id_tipo_user and self.id_tipo_user.nombre_tipo_usuario == 'Estudiante':
                if not self.Certificado:
                    raise ValidationError({
                        'Certificado': 'El certificado es obligatorio para estudiantes'
                    })

    def save(self, *args, **kwargs):
        # Si es staff, solo asignamos username si es necesario
        if self.is_staff:
            if not self.username and self.email:
                self.username = self.email.split('@')[0]
            super().save(*args, **kwargs)
            return
        
        # Para usuarios no staff, hacemos todas las validaciones
        if not self.username and self.email:
            self.username = self.email.split('@')[0]
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.email
    
    def obtenerTratamiento(self):
        # Devuelve tratamientos activos del estudiante
        return tipoTratamiento.objects.filter(
            id__in=horarios.objects.filter(
                estudiante=self,
                fecha_seleccionada__gte=datetime.now().date()
            ).values_list('tipoTratamiento_id', flat=True).distinct()
        )
    
    def is_approved(self):
        # Comprueba si el usuario está aprobado
        return self.estado_aprobacion == 'aprobado'
    
        
    def obtenerUniversidad (self):
        return Universidad.objects.get(id=self.id_universidad)['nombre']

        

    
class FichaClinica(models.Model):
    idFicha = models.BigAutoField(primary_key=True)
    paciente = models.ForeignKey(customuser, on_delete=models.SET_NULL, null=True, default=None)
    tratamiento = models.ForeignKey(tipoTratamiento, on_delete=models.SET_NULL, null=True, default=None)
    motivo_consulta = models.TextField(null=True)
    sintomas_actuales = models.TextField(null=True)
    diagnostico = models.TextField(null=True)
    tratamiento_actual = models.TextField(null=True)
    nombre_contacto_emergencia = models.TextField(null=True)
    telefono_contacto_emergencia = models.IntegerField(null=True)

    def __str__(self):
        return str(self.idFicha)








class horarios(models.Model):
    id = models.BigAutoField(primary_key=True)
    estudiante = models.ForeignKey(
        customuser, 
        on_delete=models.CASCADE, 
        related_name='horarios_estudiante',
        null=True,
        blank=True
    )
    tipoTratamiento = models.ForeignKey(
        tipoTratamiento, 
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    inicio = models.TimeField()
    fin = models.TimeField(null=True, blank=True)
    fecha_seleccionada = models.DateField()
    paciente = models.ForeignKey(
        customuser, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='horarios_paciente'
    )
    ficha_clinica = models.ForeignKey(
        'FichaClinica', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True
    )

    class Meta:
        verbose_name = 'Horario'
        verbose_name_plural = 'Horarios'

    def __str__(self):
        if self.paciente:
            return f"Cita con {self.paciente.email} el {self.fecha_seleccionada} a las {self.inicio}"
        return f"Horario disponible el {self.fecha_seleccionada} a las {self.inicio}"

# models.py

class Cita(models.Model):
    paciente = models.ForeignKey(customuser, on_delete=models.CASCADE, related_name='citas_paciente')
    estudiante = models.ForeignKey(customuser, on_delete=models.CASCADE, related_name='citas_estudiante')
    tipotratamiento = models.ForeignKey(tipoTratamiento, on_delete=models.SET_NULL, null=True)
    comuna = models.ForeignKey(Comuna, on_delete=models.SET_NULL, null=True)
    fecha_seleccionada = models.DateField()
    inicio = models.TimeField()
    direccion = models.ForeignKey(Universidad, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return f"Cita de {self.paciente.email} con {self.estudiante.email} para {self.tipotratamiento.nombreTratamiento} el {self.fecha_seleccionada} a las {self.inicio}"


class Historial_Medico(models.Model):
    idHistorial = models.BigAutoField(primary_key=True)
    paciente = models.ForeignKey(customuser, on_delete=models.SET_NULL, null=True, default=None)
    fecha_cita = models.ForeignKey(Cita, on_delete=models.SET_NULL, null=True)
    medicamentos = models.TextField(null=True)
    diagnostico = models.TextField(null=True)

    def _str_(self):
         return str(self.idHistorial)

Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/templates/autorizacion/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% block title %}Inicio Sesion{% endblock %}
{% block titulo %}Inicio Sesion{% endblock %}
{% block content %}
{% load static %}

<link type="text/css" rel="stylesheet" href='{% static "css/login_y_registro.css" %}'>
<script>

    $(document).ready(function(){

        // Función para agregar la clase g-col-6 a los elementos con la ID mencionada
        function addClassToItems() {

            var screenWidth = window.screen.width;
            var items = document.querySelectorAll("[id^='formLoginRegister']");

            if (screenWidth <= 992) {
                // Si la pantalla es menor a 992px, eliminar la clase formLoginRegister a los elementos
                items.forEach(function (item) {0
                    item.classList.remove('formLoginRegister')
                    if(item.id=='formLoginRegister-1'){
                        item.classList.remove('loginRegister')
                    }
                });
            } else {
                // Si la pantalla es mayor o igual a 992px, añadir la clase formLoginRegister de los elementos
                items.forEach(function (item) {
                    item.classList.add("formLoginRegister");
                    if(item.id=='formLoginRegister-1'){
                        item.classList.remove('loginRegister')
                    }
                });
            }
        }
        // Función para manejar el evento de cambio de tamaño de la ventana
        function handleResizeEvent() {
            // Llama a la función para agregar o eliminar la clase según el tamaño de la pantalla
            addClassToItems();
        }

        // Registrar el evento de cambio de tamaño de la ventana
        window.addEventListener("resize", handleResizeEvent);

        // Llamar a la función inicialmente al cargar la página
        addClassToItems();

    })
</script>

<!-- Bloque para mostrar mensajes de Django -->
{% if messages %}
  <div class="alert-container">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {% if "Please enter a correct email and password" in message|stringformat:"s" %}
          Por favor, ingrese un correo y contraseña correctos. Recuerde que ambos campos distinguen entre mayúsculas y minúsculas.
        {% else %}
          {{ message }}
        {% endif %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}

<!-- Bloque para errores del formulario -->
{% if form.non_field_errors %}
  <div class="alert-container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      Por favor, ingrese un correo y contraseña correctos. Recuerde que ambos campos distinguen entre mayúsculas y minúsculas.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
{% endif %}


<!--CONTENIDO HTML AQUI-->
<div id="formLoginRegister-1" class="loginRegister d-flex justify-content-center">
    <main id="formLoginRegister-2" class="form-signin w-100 formLoginRegister">
        <form method="POST" class="container-fluid">
            {% csrf_token %}
                <legend class=" mb-3">Inicio de Sesión</legend>
                    <div class="mb-3">
                        {{ form|crispy }}
                    </div>
                    <div class="form-group">
                        <button class="btn btn-lg btn-primary" type="submit">Iniciar Sesión</button>
                    </div>
        
                    <div class="row">
                        <small class="text-muted">
                            No tiene una cuenta? <a class="ml-2" href="{% url 'registro' %}">Registrarse</a>
                        </small><br>
                        <div class="mt-3">
                            <a href="{% url 'password_reset' %}" class="btn btn-secondary btn-sm">¿Olvidaste tu contraseña?</a>
                        </div>
                    </div>
                </div>
            
    
        </form>

    </main>
</div>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/templates/autorizacion/registro.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Registro{% endblock %}
{% block content %}
<link type="text/css" rel="stylesheet" href='{% static "css/login_y_registro.css" %}'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        // Mostrar u ocultar los campos de universidad, dirección y certificado según el tipo de usuario
        function toggleFields() {
            var tipoUsuario = $('#id_id_tipo_user').val();
            
            // Cambia la etiqueta del email según el tipo de usuario seleccionado
            var emailLabel = tipoUsuario == '2' ? 'Ingrese email (Ingrese Dominio Correspondiente a la Universidad Donde Estudia):' : 'Ingrese email:';
            $('label[for="id_email"]').text(emailLabel);
            
            if (tipoUsuario == '2') {  // '2' es el ID del tipo 'Estudiante', modificar si es otro
                $('#universidad-group').show();
                $('#direccion-universidad-group').show();
                $('#certificado-group').show();
            } else {
                $('#universidad-group').hide();
                $('#direccion-universidad-group').hide();
                $('#certificado-group').hide();
                $('#id_universidad').val('');
                $('#direccion-universidad').text('');
                $('#id_Certificado').val('');
            }
        }

        // Función para asociar la universidad según el correo electrónico
        function asociarUniversidad() {
            var email = $('#id_email').val();
            var dominio = email.split('@')[1];
            if (dominio == 'ug.uchile.cl') {
                $('#id_universidad').val('1');  // ID de "Universidad de Chile"
            } else if (dominio == 'ua.cl') {
                $('#id_universidad').val('2');  // ID de "Universidad Autónoma"
            } else if (dominio == 'uc.cl') {
                $('#id_universidad').val('3');  // ID de "Universidad Católica"
            } else {
                $('#id_universidad').val('');
            }
            actualizarDireccionUniversidad();
        }

        // Actualizar la dirección de la universidad seleccionada
        function actualizarDireccionUniversidad() {
            var universidadID = $('#id_universidad').val();
            if (universidadID) {
                $.ajax({
                    url: '{% url "obtener_direccion_universidad" %}',
                    data: {'universidad_id': universidadID},
                    success: function (data) {
                        $('#direccion-universidad').text(data.direccion);
                    }
                });
            } else {
                $('#direccion-universidad').text('');
            }
        }

        $('#id_id_tipo_user').change(function () {
            toggleFields();
        });

        $('#id_email').on('input', function () {
            asociarUniversidad();
        });

        toggleFields();
        actualizarDireccionUniversidad();
    });
</script>

<!-- Bloque para mostrar mensajes de Django -->
{% if messages %}
  <div class="alert-container">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}

<div class="loginRegister d-flex justify-content-center">
    <main id="formLoginRegister" class="form-signin w-100 formLoginRegister">
        <form action="{% url 'registro' %}" method="post" enctype="multipart/form-data">
            <h1>Registrarse</h1>
            {% csrf_token %}
            
            <!-- Tipo de usuario -->
            <div class="grupo">
                <label for="id_id_tipo_user">Seleccione tipo de usuario:</label>
                {{ form.id_tipo_user }}
                {% if form.id_tipo_user.errors %}
                <div class="error">{{ form.id_tipo_user.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Email -->
            <div class="grupo">
                <label for="id_email">Ingrese email:</label>
                {{ form.email }}
                {% if form.email.errors %}
                <div class="error">{{ form.email.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Campo de universidad (se muestra solo si el usuario es "Estudiante") -->
            <div class="grupo" id="universidad-group" style="display: none;">
                <label for="id_universidad">Universidad:</label>
                {{ form.universidad }}
                {% if form.universidad.errors %}
                <div class="error">{{ form.universidad.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Dirección de la universidad -->
            <div class="grupo" id="direccion-universidad-group" style="display: none;">
                <label>Dirección de la Universidad:</label>
                <p id="direccion-universidad"></p>
            </div>

            <!-- Nombre -->
            <div class="grupo">
                <label for="id_first_name">Ingrese Nombre:</label>
                {{ form.first_name }}
                {% if form.first_name.errors %}
                <div class="error">{{ form.first_name.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Apellido -->
            <div class="grupo">
                <label for="id_last_name">Ingrese Apellido:</label>
                {{ form.last_name }}
                {% if form.last_name.errors %}
                <div class="error">{{ form.last_name.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Número de teléfono -->
            <div class="grupo">
                <label for="id_num_tel">Ingrese Número (9 dígitos):</label>
                {{ form.num_tel }}
                {% if form.num_tel.errors %}
                <div class="error">{{ form.num_tel.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Dirección de residencia -->
            <div class="grupo">
                <label for="id_direccion">Ingrese su Dirección:</label>
                {{ form.direccion }}
                {% if form.direccion.errors %}
                <div class="error">{{ form.direccion.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Comuna -->
            <div class="grupo">
                <label for="id_comuna">Ingrese Comuna:</label>
                {{ form.comuna }}
                {% if form.comuna.errors %}
                <div class="error">{{ form.comuna.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Fecha de nacimiento -->
            <div class="form-grupo">
                <label for="id_fecha_nac">Ingrese Fecha de Nacimiento:</label>
                {{ form.fecha_nac }}
                {% if form.fecha_nac.errors %}
                <div class="error">{{ form.fecha_nac.errors|join:", " }}</div>
                {% endif %}
            </div>
            
            <!-- Contraseña -->
            <div class="grupo">
                <label for="id_password1">Ingrese Contraseña:</label>
                {{ form.password1 }}
                {% if form.password1.errors %}
                <div class="error">{{ form.password1.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Confirmación de contraseña -->
            <div class="grupo">
                <label for="id_password2">Confirme Contraseña:</label>
                {{ form.password2 }}
                {% if form.password2.errors %}
                <div class="error">{{ form.password2.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- RUT -->
            <div class="grupo">
                <label for="id_rut">Ingrese RUT:</label>
                {{ form.rut }}
                {% if form.rut.errors %}
                <div class="error">{{ form.rut.errors|join:", " }}</div>
                {% endif %}
            </div>

            <!-- Certificado (solo para estudiantes) -->
            <div class="grupo" id="certificado-group" style="display: none;">
                <label for="id_Certificado">Certificado PDF:</label>
                {{ form.Certificado }}
                {% if form.Certificado.errors %}
                <div class="error">{{ form.Certificado.errors|join:", " }}</div>
                {% endif %}
            </div>

            <div class="form-group">
                <label for="{{ form.captcha.id_for_label }}">Verificación de seguridad</label>
                {{ form.captcha }}
                {% if form.captcha.errors %}
                    <div class="alert alert-danger">
                        {{ form.captcha.errors }}
                    </div>
                {% endif %}
            </div>
            
            <button type="submit" class="registerbtn">Enviar</button>
        </form>
    </main>
</div>
{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/templates/autorizacion/revisar_estudiantes.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <h2>Verificación de Estudiantes</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Email</th>
                <th>Certificado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for estudiante in estudiantes_pendientes %}
            <tr>
                <td>{{ estudiante.first_name }} {{ estudiante.last_name }}</td>
                <td>{{ estudiante.email }}</td>
                <td>
                    {% if estudiante.Certificado %}
                        <a href="{{ estudiante.Certificado.url }}" target="_blank" class="btn btn-info btn-sm">
                            Ver Certificado de Alumno
                        </a>
                    {% else %}
                        <span>No disponible</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'actualizar_estado_estudiante' estudiante.id 'aprobado' %}" class="btn btn-success">Aprobar</a>
                    <a href="{% url 'actualizar_estado_estudiante' estudiante.id 'rechazado' %}" class="btn btn-danger">Rechazar</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">No hay estudiantes pendientes de revisión.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}