Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/urls.py
from django.contrib import admin
from django.urls import path, include # Setup include to allow other app's urls to 
from . import views # COMO QUE NO EXISTE? XD

from django.conf import settings
from django.conf.urls.static import static
from .views import *
from ProyectoAPT.views import filtrar_estudiantes
from django.contrib.auth import views as auth_views




urlpatterns = [
    path('', views.index, name='index'),
    # Horarios
    path('horarios/', views.registroHoras, name='horarios'),
    path('Horarios/<int:estudianteID>', views.tratamientosForm, name='tratamientosEstudiante'),
    # There we will enable the horario LIST
    path('obtener-horarios-disponibles/', views.obtener_horarios_disponibles, name='obtener_horarios_disponibles'),
    

    # Eliminar horario
    path('eliminar-horario/<int:horario_id>/', views.eliminar_horario, name='eliminar_horario'),



    # AUTH
    path('login/', views.loginUser, name='login'),
    path('registro/', views.register, name='registro'),
    path('logout/', views.custom_logout, name='logout'),
    path('obtener-direccion-universidad/', views.obtener_direccion_universidad, name='obtener_direccion_universidad'),
    path('revisar_estudiantes/', views.revisar_estudiantes, name='revisar_estudiantes'),
    #aptcha
    path('captcha/', include('captcha.urls')),
    #Servicios
    path('servicios/', views.servicios, name='servicios'),

    

    #Citas Paciente
    path('citas/', views.citas_pac, name='citas'),
    path('cita/anular/<int:cita_id>/', views.anular_cita, name='anular_cita'),

    # Añadir a subPage de Estudiante....
    path('estudiante/infopersonal/', views.infoestudiante, name="infoestudiante"),
    path('estudiante/notificaciones_estudiante/', views.notifiaciones_est, name="notificaciones"),
    path('estudiante/pacientes_estudiante/', views.pacientes_est, name="pacientes_est"),
    path('estudiante/calendario_est/',  views.calendar_est, name="calendario"), 
    path('crear_historial_medico/<int:paciente_id>/', views.crear_historial_medico, name='crear_historial_medico'),
    path('filtrar-estudiantes/', views.filtrar_estudiantes, name='filtrar_estudiantes'),


    #crear ficha paciente
    path('crear-ficha/<int:user_id>/', views.crear_ficha_paciente, name='crear_ficha_paciente'),
    path('lista_fichas_clinicas/', views.ver_ficha_clinica, name='lista_fichas_clinicas'),
    path('fichaExportar/<int:user_id>', views.exportar_ficha_paciente, name='fichaExportar'),
    #eliminar paciente
    path('eliminar-paciente/<int:paciente_id>/', views.eliminar_paciente, name='eliminar_paciente'),
    path('horarios/', filtrar_estudiantes, name='horarios'),  
    path('ver_ficha_clinica/<int:paciente_id>/', views.ver_ficha_clinica, name='ver_ficha_clinica'),
    

    # contraseña olvidada
    path('olvide-password/', 
        auth_views.PasswordResetView.as_view(
            template_name='login/olvide-pass.html',
            email_template_name='login/pass_email_reset.html',
            subject_template_name='login/password_reset_subject.txt',
        ),
        name='password_reset'
    ),
    path('reset-password-enviado/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='login/pass_confirm_email.html'
        ),
        name='password_reset_done'
    ),
    path('reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='login/reset-pass.html'
        ),
        name='password_reset_confirm'
    ),
    path('reset-password-completado/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='login/pass_complete.html'
        ),
        name='password_reset_complete'
    ),
    ]
# Solo en modo de desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/forms.py
## USER CREATION FORM
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordResetForm #importa autenticacion de forms
from .models import * #importa modelos
from django import forms #importa formularios
from typing import Any #Te entrega todo (preguntarle a chatgpt)
from django.utils import timezone
from datetime import datetime, timedelta, time
from django.core.validators import FileExtensionValidator
from django.conf import settings

# Set default values to use:
inicioB = ["",time(9,0), time(11,0), time(13,0), time(15,0), time(17,00), time(19,00)]
inicioA = ["", str(time(9,0).strftime('%H:%M:%S') + ' - ' + time(10,59).strftime('%H:%M:%S')), 
           str(time(11,0).strftime('%H:%M:%S') + ' - ' + time(12,59).strftime('%H:%M:%S')), 
           str(time(13,0).strftime('%H:%M:%S') + ' - ' + time(14,59).strftime('%H:%M:%S')), 
           str(time(15,0).strftime('%H:%M:%S') + ' - ' + time(16,59).strftime('%H:%M:%S')),
           str(time(17,0).strftime('%H:%M:%S') + ' - ' + time(18,59).strftime('%H:%M:%S'))]



from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import customuser
from captcha.fields import CaptchaField

class CustomUserCreationForm(UserCreationForm):
    captcha = CaptchaField(label='Ingrese el texto de la imagen')
    class Meta:
        model = customuser
        fields = ['first_name', 'last_name', 'email', 'rut', 'id_tipo_user', 'password1', 'password2', 'num_tel', 'fecha_nac', 'direccion', 'comuna', 'universidad', 'Certificado']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Si estamos editando un usuario existente y tiene comuna
        if self.instance and self.instance.comuna:
            # Convertir el campo comuna a un campo de texto de solo lectura
            self.fields['comuna'] = forms.CharField(
                initial=self.instance.comuna.nombreComuna,
                widget=forms.TextInput(attrs={
                    'class': 'form-control',
                    'readonly': True,
                    'id': 'id_comuna'
                })
            )
        else:
            # Si es un nuevo usuario, mantener el select normal
            self.fields['comuna'] = forms.ModelChoiceField(
                queryset=Comuna.objects.all().order_by('nombreComuna'),
                empty_label="Seleccione una comuna",
                required=False,
                widget=forms.Select(attrs={
                    'class': 'form-control',
                    'id': 'id_comuna'
                })
            )

        self.fields['email'].widget.attrs.update({'placeholder': 'Email'})
        self.fields['first_name'].widget.attrs.update({'placeholder': 'Nombre'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Apellido'})

        self.fields['fecha_nac'] = forms.DateField(
            label="Seleccione su fecha!",
            required=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_fecha_seleccionada', 'type': 'date', }),
        )
        self.fields['fecha_nac'].widget.attrs.update({'class': 'form-control', 'type':'date'})   
        self.fields['num_tel'].widget.attrs.update({'placeholder': 'Ingrese Número - 9 digitos','min':'4'})
        self.fields['direccion'].widget.attrs.update({'placeholder': 'Ingrese Su Direccion'})
        self.fields['rut'].widget.attrs.update({'placeholder': 'RUT'})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Contraseña'})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Confirmar Contraseña'})
        self.fields['universidad'].widget.attrs.update({'placeholder': 'Universidad'})
        self.fields['Certificado'].widget.attrs.update({
            'class': 'form-control',
            'accept': '.pdf,application/pdf',
            'placeholder': 'Seleccione un archivo PDF'
        })

    def clean(self):
        cleaned_data = super().clean()
        tipo_usuario = cleaned_data.get('id_tipo_user')
        documento = cleaned_data.get('Certificado')
        comuna = cleaned_data.get('comuna')
        
        # Validación del certificado para estudiantes
        if tipo_usuario and tipo_usuario.id == 2:  # ID para estudiante
            if not documento:
                raise forms.ValidationError(
                    "El documento PDF es obligatorio para estudiantes."
                )
        
        # Validación de comuna para no-staff
        if tipo_usuario and tipo_usuario.id != 1 and not comuna:  # Si no es staff
            self.add_error('comuna', 'Por favor seleccione una comuna')

        return cleaned_data



class FichaClinicaForm(forms.ModelForm):
    class Meta:
        model = FichaClinica
        fields = ['nombre_contacto_emergencia', 'telefono_contacto_emergencia', 'motivo_consulta', 'sintomas_actuales', 'diagnostico', 'tratamiento_actual']

    def __init__(self, *args, **kwargs):
        super(FichaClinicaForm, self).__init__(*args, **kwargs)
        self.fields['nombre_contacto_emergencia'].widget.attrs.update({'placeholder': 'Persona en caso de emergencia'})

        self.fields['telefono_contacto_emergencia'].widget.attrs.update({'placeholder': 'Contacto de emergencia'})   

        self.fields['motivo_consulta'].widget.attrs.update({'placeholder': 'Ingrese Motivo'})
        self.fields['sintomas_actuales'].widget.attrs.update({'placeholder': 'Ingrese Sintomas'})
        self.fields['diagnostico'].widget.attrs.update({'placeholder': 'Ingrese Diagnostico'})


        

        

class UserLoginForm(AuthenticationForm):
    username = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    def clean_username(self):
        email = self.cleaned_data.get('username')
        if not customuser.objects.filter(email=email).exists():
            raise forms.ValidationError("No existe un usuario con este email.")
        return email
    

    
class horariosForm(forms.ModelForm):
    # Generamos los intervalos de 15 minutos para que el usuario elija
    def generar_opciones_horario():
        opciones = []
        hora_actual = time(8, 0)  # Hora de inicio
        while hora_actual <= time(20, 0):  # Hora de fin
            opciones.append((hora_actual.strftime('%H:%M'), hora_actual.strftime('%H:%M')))
            hora_actual = (datetime.combine(date.today(), hora_actual) + timedelta(minutes=60)).time()
        return opciones

    inicio = forms.ChoiceField(
        choices=generar_opciones_horario(),
        label="Hora de Inicio",
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True  # Campo obligatorio
    )
    fin = forms.ChoiceField(
        choices=generar_opciones_horario(),
        label="Hora de Fin",
        widget=forms.Select(attrs={'class': 'form-control'}),
        required=True  # Campo obligatorio
    )

    class Meta:
        model = horarios
        fields = ['tipoTratamiento', 'inicio', 'fin']
        widgets = {
            'tipoTratamiento': forms.Select(attrs={
                'class': 'form-control'
            }),
        }

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tipoTratamiento'].label = "Tipo de Tratamiento"
        self.fields['tipoTratamiento'].required = True  # Campo obligatorio

        # Filtrar tratamientos basados en los del perfil del estudiante
        if user and user.tratamientos.exists():
            self.fields['tipoTratamiento'].queryset = user.tratamientos.all()
        else:
            self.fields['tipoTratamiento'].queryset = tipoTratamiento.objects.none()

    def clean(self):
        cleaned_data = super().clean()
        inicio = cleaned_data.get('inicio')
        fin = cleaned_data.get('fin')

        if inicio and fin:
            # Convertir los valores de las horas en objetos de tiempo para la comparación
            hora_inicio = datetime.strptime(inicio, '%H:%M').time()
            hora_fin = datetime.strptime(fin, '%H:%M').time()
            if hora_fin <= hora_inicio:
                self.add_error('fin', 'La hora de fin debe ser posterior a la hora de inicio')
        else:
            if not inicio:
                self.add_error('inicio', 'Este campo es obligatorio')
            if not fin:
                self.add_error('fin', 'Este campo es obligatorio')

        return cleaned_data

class CitaForm(forms.ModelForm):
    class Meta:
        model = Cita
        fields =[
            'tipotratamiento',
            'inicio',
            'fecha_seleccionada',
            'estudiante',
            'paciente']

    def __init__(self, *args: Any, **kwargs):
        super(CitaForm, self).__init__(*args, **kwargs)
        #Add tipo de tratamiento
        self.fields['tipotratamiento'] = forms.ModelChoiceField(
            queryset=tipoTratamiento.objects.all(),
            empty_label="Seleccione un Tratamiento",
            widget=forms.Select(attrs={'class':'form-control','id':'nombreTratamiento'})
        )
        self.fields['tipotratamiento'].label = "Tipo de tratamiento"

        self.fields['fecha_seleccionada'] = forms.DateField(
            label="Seleccione su fecha!",
            required=True,
            widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_fecha_seleccionada', 'type': 'date', }),

        )
        self.fields['fecha_seleccionada'].widget.attrs.update({'class': 'form-control', 'type':'date'})
        idTipoEstudiante = TipoUsuario.objects.filter(nombre_tipo_usuario='Estudiante').first()
        self.fields['estudiante'] = forms.ModelChoiceField(
            queryset=customuser.objects.filter(id_tipo_user=idTipoEstudiante), #Modificable
            empty_label=None,
            widget=forms.Select(attrs={'class':'form-control', 'hidden':True})
        )

Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/templates/APT/citas.html
{% extends "base.html" %}
{% block content %}
<main>

    {% if messages %}
        <div>
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    
    <div class="container mt-5">
        <h2>Mis Citas</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Estudiante</th>
                    <th>Tipo de Tratamiento</th>
                    <th>Fecha</th>
                    <th>Hora</th>
                    <th>Dirección</th>
                    <th>Comuna</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for cita in citas %}
                <tr>
                    <td>{{ cita.estudiante.first_name }} {{ cita.estudiante.last_name }}</td>
                    <td>{{ cita.tipotratamiento.nombreTratamiento }}</td>
                    <td>{{ cita.fecha_seleccionada }}</td>
                    <td>{{ cita.inicio }}</td>
                    <td>{{ cita.estudiante.universidad.direccion }}</td>
                    <td>{{ cita.comuna.nombreComuna }}</td>
                    <td>
                        <a href="{% url 'anular_cita' cita.id %}" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que deseas anular esta cita?');">
                            Anular
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="7">No tienes citas agendadas.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/templates/APT/horarios.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/filtro.css' %}">
</head>

<main>

    <div class="content-panel">
        <div class="container">
            <h2>Filtrar Estudiantes</h2>

            <!-- Contenedor del filtro -->
            <form id="filterForm" method="get" action="{% url 'filtrar_estudiantes' %}">
                <div class="filtro-container">
                    <input type="text" id="searchInput" name="q" placeholder="Buscar estudiante..." onkeyup="filterServices()" />



                    <select id="universitySelect" name="universidad"
                        style="display: inline-block !important; visibility: visible !important;">
                        <option value="">Todas las Universidades</option>
                        {% for universidad in universidades %}
                        <option value="{{ universidad.id }}">{{ universidad.nombre }}</option>
                        {% endfor %}
                    </select>

                    <select id="treatmentSelect" name="tratamiento">
                        <option value="">Todos los Tratamientos</option>
                        {% for tratamiento in tratamientos %}
                        <option value="{{ tratamiento.id }}">{{ tratamiento.nombreTratamiento }}</option>
                        {% endfor %}
                    </select>

                    <button type="submit">Filtrar</button>
                </div>
            </form>
<!-- Lista de estudiantes con filtro aplicado -->
            <div id="servicesList">
                {% if estudiantes %}
                {% for estudiante in estudiantes %}
                <div class="col-md-4 servicio" data-university="{{ estudiante.universidad.id }}"
                    data-treatment="{{ estudiante.tratamientos.all|join:',' }}">
                    <div class="card">
                        <div class="card-header">
                            {% if estudiante.imageBlob %}
                            <img src="{{ estudiante.imageBlob.url }}" alt="Imagen del estudiante" width="150"
                                height="150">
                            {% else %}
                            <img src="{% static 'path/to/default/image.png' %}" alt="Imagen por defecto" width="150"
                                height="150"> <!-- Cambia el path a tu imagen por defecto -->
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <h3 class="card-title">{{ estudiante.first_name }} {{ estudiante.last_name }}</h3>
                            <p class="card-text">{{ estudiante.descripcion|linebreaksbr }}</p>
                            <p>Universidad: {{ estudiante.universidad.nombre }}</p>
                            <p>Tratamientos Disponibles:</p>
                            <ul>
                                {% for tratamiento in estudiante.obtenerTratamiento %}
                                <li>{{ tratamiento.nombreTratamiento }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'tratamientosEstudiante' estudiante.id %}" class="btn btn-primary">Agendar
                                Cita</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <p>No se encontraron estudiantes que coincidan con los criterios de búsqueda.</p>
                {% endif %}
            </div>
        </div>
    </div>
</main>

<script src="{% static 'js/filtro.js' %}"></script>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de Sistema/Aplicación/IODONT/proyecto_apt/ProyectoAPT/templates/APT/horariosEstudianteTratamiento.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}

<!-- Incluir FullCalendar y SweetAlert2 -->
<link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.css' rel='stylesheet' />
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/locales/es.js'></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<link rel="stylesheet" href="{% static 'css/agenda_cita.css' %}">
{# Agregar esto cerca del inicio del contenido #}
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}
<div class="container">
    <h2 class="titulo-principal">¿QUÉ SERVICIO NECESITA AGENDAR?</h2>
    <p class="subtitulo">Elige el servicio que necesitas agendar</p>

    <form method="post">
        {% csrf_token %}
        <!-- En la sección de los tratamientos -->
        <div class="servicios-grid">
            {% for tratamiento in estudiante.obtenerTratamiento %}
                <div class="servicio-card">
                    <div class="icono">
                        <i class="fas fa-tooth"></i>
                    </div>
                    <h3>{{ tratamiento.nombreTratamiento }}</h3>
                    <p>Servicio dental profesional</p>
                    <button type="button"
                        class="btn-servicio"
                        onclick="mostrarCalendario('{{ tratamiento.id }}', '{{ tratamiento.nombreTratamiento }}')"
                    >Seleccionar</button>
                </div>
            {% endfor %}
        </div>

        <!-- Campos ocultos del formulario -->
        <div class="row" id="hiddenValues">
            <input type="hidden" name="tratamiento" id="id_tratamiento">
            <input type="hidden" name="tipotratamiento" id="nombreTratamiento">
            <input type="hidden" name="fecha_seleccionada" id="id_fecha_seleccionada">
            <input type="hidden" name="paciente" id="id_paciente" value="{{ actualUser }}">
            <input type="hidden" name="estudiante" id="id_estudiante" value="{{ estudiante.id }}">
            <input type="hidden" name="inicio" id="id_inicio">
        </div>
    </form>

    <!-- Calendario oculto inicialmente -->
    <div id="calendario-container" style="display: none;">
        <h3 id="tratamiento-seleccionado"></h3>
        <div id="calendar"></div>
    </div>

    <!-- Modal para horarios -->
    <div class="modal fade" id="horariosModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Horarios Disponibles</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div id="horarios-lista"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="confirmarCita()">Agendar</button>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
let calendar;

function mostrarCalendario(tratamientoId, nombreTratamiento) {
    document.getElementById('calendario-container').style.display = 'block';
    document.getElementById('tratamiento-seleccionado').textContent = nombreTratamiento;
    
    document.getElementById('id_tratamiento').value = tratamientoId;
    document.getElementById('nombreTratamiento').value = tratamientoId;
    
    if (calendar) {
        calendar.destroy();
    }
    
    fetch(`/obtener-horarios-disponibles/?tratamiento_id=${tratamientoId}&estudiante_id={{ estudiante.id }}`)
        .then(response => response.json())
        .then(data => {
            inicializarCalendario(tratamientoId, data);
        });
}

function inicializarCalendario(tratamientoId, diasDisponibles) {
    console.log("Días disponibles recibidos:", diasDisponibles);
    
    var calendarEl = document.getElementById('calendar');
    calendar = new FullCalendar.Calendar(calendarEl, {
        locale: 'es',
        initialView: 'dayGridMonth',
        selectable: true,
        headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth'
        },
        dayCellDidMount: function(arg) {
            const fecha = arg.date.toISOString().split('T')[0];
            console.log("Verificando fecha:", fecha);
            
            const esDiaDisponible = diasDisponibles.some(d => {
                const fechaDisponible = d.fecha_seleccionada;
                console.log("Comparando con:", fechaDisponible);
                return fechaDisponible === fecha;
            });
            
            if (esDiaDisponible) {
                console.log("Día disponible encontrado:", fecha);
                arg.el.classList.add('dia-disponible');
                // Intentar forzar el estilo directamente
                arg.el.style.backgroundColor = '#e8f4ff';
                arg.el.style.cursor = 'pointer';
            }
        },
        dateClick: function(info) {
            if (info.dayEl.classList.contains('dia-disponible')) {
                mostrarHorariosDisponibles(tratamientoId, info.dateStr);
            }
        }
    });
    
    calendar.render();
}

function mostrarHorariosDisponibles(tratamientoId, fecha) {
    document.getElementById('id_fecha_seleccionada').value = fecha;
    
    fetch(`/obtener-horarios-disponibles/?tratamiento_id=${tratamientoId}&fecha_seleccionada=${fecha}&estudiante_id={{ estudiante.id }}`)
        .then(response => response.json())
        .then(data => {
            var horariosHtml = '';
            if (data.length > 0) {
                data.forEach(horario => {
                    // Solo mostrar el horario si está realmente disponible
                    if (!horario.reservado) {
                        horariosHtml += `
                            <button type="button" class="btn btn-outline-primary m-1" 
                                    onclick="seleccionarHorario('${horario.inicio}')">
                                ${horario.inicio}
                            </button>`;
                    }
                });
                // Si no hay horarios disponibles después del filtrado
                if (horariosHtml === '') {
                    horariosHtml = '<p>No hay horarios disponibles para esta fecha</p>';
                }
            } else {
                horariosHtml = '<p>No hay horarios disponibles para esta fecha</p>';
            }
            document.getElementById('horarios-lista').innerHTML = horariosHtml;
            new bootstrap.Modal(document.getElementById('horariosModal')).show();
        });
}

function seleccionarHorario(hora) {
    document.getElementById('id_inicio').value = hora;
    document.querySelectorAll('#horarios-lista button').forEach(btn => {
        btn.classList.remove('btn-primary');
        btn.classList.add('btn-outline-primary');
        if (btn.textContent.trim() === hora) {
            btn.classList.remove('btn-outline-primary');
            btn.classList.add('btn-primary');
        }
    });
}

function confirmarCita() {
    const form = document.querySelector('form');
    const formData = new FormData(form);

    if (!formData.get('tipotratamiento') || !formData.get('fecha_seleccionada') || !formData.get('inicio')) {
        Swal.fire({
            title: 'Error',
            text: 'Por favor, selecciona todos los campos necesarios',
            icon: 'error'
        });
        return;
    }

    form.submit();
}
</script>



{% endblock %}